### ISSUE TITLE
Soccer issues

### ISSUE THREAD

**Issue by hs8945** [erilyth/Soccer-Player-Segmentation#1]
Why you choose 3 primeter as a standard?Do you have any reliable basis?Also about<20*primeter this parameter.Thanks for your answer.

**Comment by erilyth** [comment]
@hs8945 The area/perimeter ratio was used to determine the roundness of an object. With the data I had available I just tried out a few samples and choose the one that fit best to my data. In this case I chose 3 and it turned out to work decently on unseen data as well during my evaluations of the project.

**Comment by hs8945** [comment]
OK, I get it. This method is very insteresting ande useful. And thanks for your answer again.

**Comment by erilyth** [comment]
@hs8945 Welcome :)
